### ISSUE TITLE
Cancel/Abort button while plugin is running

### ISSUE THREAD

**Issue by dsethz** [pyapp-kit/magicgui#489]
Hey,

This is my first time working with `magicgui`, so maybe this option exists already (but I could not find it in the documentation):

Change "Run" button to "Cancel"/"Abort" button while the widget function is executed.

This would be very cool to have for any plugin that is intended to run for minutes/hours (e.g. segmentation of multiple images, etc.).

Best,
Daniel

**Comment by dsethz** [comment]
Hey @tlambert03,

Thank you for the quick response and the links. I will check them out. :)  

I see your points. This is probably a naive question (I am very new to software engineering): Would it be a feasible solution to run every magicgui plugin by default on a separate thread and have a single handle (e.g. class attribute of `@magicgui`/`FunctionGui`) to manage the cancel/abort functionality? That way no extensive multi-threading functionality is given to the user, but users may in a standardised and easily accessible way handle cancel/abort mechanics (and would not need to know about the underlying multi-threading solution?). Further, users would still have to set up their plugin to gracefully exit the computation and no guessing about plugin architecture would be necessary on the magicgui side.

**Comment by tlambert03** [comment]
> Would it be a feasible solution to run every magicgui plugin by default on a separate thread and have a single handle to manage the cancel/abort functionality

just to clarify some wording here.  magicgui doesn't have "plugins".  _napari_ has plugins, some of which use magicgui to generate their interfaces.  When you say plugin here, are you referring to napari plugin?  or just a widget generated by magicgui.

In any case, I think the answer is broadly the same: feasible? yes probably... but concurrency is really not trivial at all, and it would be a really big lift here, and whether it's in scope for a library that only focuses on mapping python types to widgets is a big question.  My opinion is that it's out of scope for magicgui, but that napari might try to offer something like that.

**Comment by dsethz** [comment]
I was referring to the magicgui widget, but I see your point and how this may be better located at napari. Thank you :)
