### ISSUE TITLE
guiclass not updating model `Path` parameters

### ISSUE THREAD

**Issue by alisterburt** [pyapp-kit/magicgui#555]
**Describe the bug**
For a class decorated with the experimental `@guiclass` decorator modifying the value of an attribute decorated as `Path` does not update the value on the model

**To Reproduce**

```python
from pathlib import Path

import napari
from magicgui.experimental import guiclass
from magicgui.widgets import Button


@guiclass
class MyGuiClass:
    a: Path = Path('blabla')


gui = MyGuiClass()

def printer():
    print(gui.a.resolve())

button = Button(text='print path')
button.clicked.connect(printer)
gui.gui.append(button)
gui.gui.show()
napari.run()
```

sorry for the napari, easiest way I know to get an event loop 😆 

**Expected behavior**
Model should be updated

**Screenshots**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/7307488/234064964-e43a2054-9ace-415b-b718-3f2f7912264b.png">

**Environment (please complete the following information):**
 - OS: Mac
 - backend: Qt 5.15.6
 - magicgui version 0.7.2

**Comment by tlambert03** [comment]
> sorry for the napari, easiest way I know to get an event loop 😆

**Comment by alisterburt** [comment]
thanks! good to know 🙂
