### ISSUE TITLE
Having trouble with unresponsive magicgui dialog boxes in jupyter notebook

### ISSUE THREAD

**Issue by wjnicol** [pyapp-kit/magicgui#568]
Hello there,

I recently got into coding using napari and other related python tools. I am trying to make a CLEM workflow more streamlined for my lab and have been doing so using Napari. I would like to use MagicGui to have dialog boxes pop up to choose input file, output folder etc. When I do so in a jupyter notebook, the dialog box is printed out underneath the code cell but the dialog box is unresponsive and says “Not responding”. Ultimately trying to close it breaks the kernel.

![Screenshot 2023-07-24 180553](https://github.com/pyapp-kit/magicgui/assets/75800946/323c2a7e-217c-4781-addf-03b945d6276b).

I am running this on a windows computer with VS code within an environment created to run Napari and the 3D-Correlation Toolbox suite. For what it’s worth this is the output of $conda list:

#Name Version Build Channel
alabaster 0.7.13 pypi_0 pypi
aom 3.5.0 h63175ca_0 conda-forge
app-model 0.2.0 pypi_0 pypi
appdirs 1.4.4 pypi_0 pypi
asttokens 2.2.1 pypi_0 pypi
attrs 23.1.0 pypi_0 pypi
babel 2.12.1 pypi_0 pypi
backcall 0.2.0 pypi_0 pypi
beautifulsoup4 4.12.2 pyha770c72_0 conda-forge
blosc 1.21.4 hdccc3a2_0 conda-forge
boltons 23.0.0 pyhd8ed1ab_0 conda-forge
brotli-python 1.0.9 py39h99910a6_9 conda-forge
build 0.10.0 pypi_0 pypi
bzip2 1.0.8 h8ffe710_4 conda-forge
c-blosc2 2.10.0 h183a6f4_0 conda-forge
ca-certificates 2023.7.22 h56e8100_0 conda-forge
cachey 0.2.1 pypi_0 pypi
cairo 1.16.0 hdecc03f_1016 conda-forge
certifi 2023.7.22 pyhd8ed1ab_0 conda-forge
cffi 1.15.1 py39h68f70e3_3 conda-forge
cfitsio 4.2.0 h9ebe7e4_0 conda-forge
chardet 5.1.0 py39hcbf5309_0 conda-forge
charls 2.4.2 h1537add_0 conda-forge
charset-normalizer 3.2.0 pyhd8ed1ab_0 conda-forge
click 8.1.5 win_pyh7428d3b_0 conda-forge
cloudpickle 2.2.1 pyhd8ed1ab_0 conda-forge
colorama 0.4.6 pyhd8ed1ab_0 conda-forge
comm 0.1.3 pypi_0 pypi
conda 23.5.2 py39hcbf5309_0 conda-forge
conda-build 3.25.0 py39hcbf5309_0 conda-forge
conda-index 0.2.3 pyhd8ed1ab_0 conda-forge
conda-package-handling 2.0.2 pyh38be061_0 conda-forge
conda-package-streaming 0.8.0 pyhd8ed1ab_0 conda-forge
cryptography 41.0.2 py39hb6bd5e6_0 conda-forge
cycler 0.11.0 pyhd8ed1ab_0 conda-forge
cytoolz 0.12.0 py39ha55989b_1 conda-forge
dask-core 2023.7.0 pyhd8ed1ab_0 conda-forge
dav1d 1.2.1 hcfcfb64_0 conda-forge
debugpy 1.6.7 pypi_0 pypi
decorator 5.1.1 pypi_0 pypi
docstring-parser 0.15 pypi_0 pypi
docutils 0.17.1 pypi_0 pypi
executing 1.2.0 pypi_0 pypi
expat 2.5.0 h63175ca_1 conda-forge
ffmpeg 6.0.0 gpl_h2b371f0_103 conda-forge
filelock 3.12.2 pyhd8ed1ab_0 conda-forge
font-ttf-dejavu-sans-mono 2.37 hab24e00_0 conda-forge
font-ttf-inconsolata 3.000 h77eed37_0 conda-forge
font-ttf-source-code-pro 2.038 h77eed37_0 conda-forge
font-ttf-ubuntu 0.83 hab24e00_0 conda-forge
fontconfig 2.14.2 hbde0cde_0 conda-forge
fonts-conda-ecosystem 1 0 conda-forge
fonts-conda-forge 1 0 conda-forge
freeglut 3.2.2 h63175ca_2 conda-forge
freetype 2.12.1 h546665d_1 conda-forge
freetype-py 2.4.0 pypi_0 pypi
fsspec 2023.6.0 pyh1a96a4e_0 conda-forge
gettext 0.21.1 h5728263_0 conda-forge
giflib 5.2.1 h64bf75a_3 conda-forge
glib 2.76.4 h12be248_0 conda-forge
glib-tools 2.76.4 h12be248_0 conda-forge
glob2 0.7 py_0 conda-forge
graphite2 1.3.13 1000 conda-forge
gst-plugins-base 1.22.4 h001b923_1 conda-forge
gstreamer 1.22.4 hb4038d2_1 conda-forge
harfbuzz 7.3.0 h196d34a_0 conda-forge
hdf5 1.14.1 nompi_h73e8ff5_100 conda-forge
heapdict 1.0.1 pypi_0 pypi
hsluv 5.0.3 pypi_0 pypi
icu 72.1 h63175ca_0 conda-forge
idna 3.4 pyhd8ed1ab_0 conda-forge
imagecodecs 2023.1.23 py39hd475b99_2 conda-forge
imageio 2.31.1 pyh24c5eb1_0 conda-forge
imagesize 1.4.1 pypi_0 pypi
importlib-metadata 6.8.0 pyha770c72_0 conda-forge
importlib_metadata 6.8.0 hd8ed1ab_0 conda-forge
in-n-out 0.1.8 pypi_0 pypi
intel-openmp 2023.1.0 h57928b3_46319 conda-forge
ipykernel 6.24.0 pypi_0 pypi
ipython 8.14.0 pypi_0 pypi
ipython-genutils 0.2.0 pypi_0 pypi
jasper 4.0.0 h00710e9_1 conda-forge
jedi 0.18.2 pypi_0 pypi
jinja2 3.1.2 pyhd8ed1ab_1 conda-forge
jsonpatch 1.32 pyhd8ed1ab_0 conda-forge
jsonpointer 2.0 py_0 conda-forge
jsonschema 4.18.4 pypi_0 pypi
jsonschema-specifications 2023.7.1 pypi_0 pypi
jupyter-client 8.3.0 pypi_0 pypi
jupyter-core 5.3.1 pypi_0 pypi
jxrlib 1.1 h8ffe710_2 conda-forge
kiwisolver 1.4.4 py39h1f6ef14_1 conda-forge
krb5 1.20.1 heb0366b_0 conda-forge
lazy-loader 0.3 pypi_0 pypi
lcms2 2.15 h3e3b177_1 conda-forge
lerc 4.0.0 h63175ca_0 conda-forge
libaec 1.0.6 h63175ca_1 conda-forge
libarchive 3.6.2 h6f8411a_1 conda-forge
libavif 0.11.1 ha7b97ba_2 conda-forge
libblas 3.9.0 17_win64_mkl conda-forge
libbrotlicommon 1.0.9 hcfcfb64_9 conda-forge
libbrotlidec 1.0.9 hcfcfb64_9 conda-forge
libbrotlienc 1.0.9 hcfcfb64_9 conda-forge
libcblas 3.9.0 17_win64_mkl conda-forge
libclang 16.0.6 default_heb8d277_0 conda-forge
libclang13 16.0.6 default_hc80b9e7_0 conda-forge
libcurl 8.1.2 h68f0423_0 conda-forge
libdeflate 1.18 hcfcfb64_0 conda-forge
libexpat 2.5.0 h63175ca_1 conda-forge
libffi 3.4.2 h8ffe710_5 conda-forge
libglib 2.76.4 he8f3873_0 conda-forge
libhwloc 2.9.1 nocuda_h15da153_6 conda-forge
libiconv 1.17 h8ffe710_0 conda-forge
libjpeg-turbo 2.1.5.1 hcfcfb64_0 conda-forge
liblapack 3.9.0 17_win64_mkl conda-forge
liblapacke 3.9.0 17_win64_mkl conda-forge
liblief 0.12.3 h63175ca_0 conda-forge
libogg 1.3.4 h8ffe710_1 conda-forge
libopencv 4.7.0 py39hbd58657_6 conda-forge
libopus 1.3.1 h8ffe710_1 conda-forge
libpng 1.6.39 h19919ed_0 conda-forge
libprotobuf 3.21.12 h12be248_0 conda-forge
libsqlite 3.42.0 hcfcfb64_0 conda-forge
libssh2 1.11.0 h7dfc565_0 conda-forge
libtiff 4.5.1 h6c8260b_0 conda-forge
libvorbis 1.3.7 h0e60522_0 conda-forge
libwebp-base 1.3.1 hcfcfb64_0 conda-forge
libxcb 1.15 hcd874cb_0 conda-forge
libxml2 2.11.4 hc3477c8_0 conda-forge
libzlib 1.2.13 hcfcfb64_5 conda-forge
libzopfli 1.0.3 h0e60522_0 conda-forge
locket 1.0.0 pyhd8ed1ab_0 conda-forge
lz4-c 1.9.4 hcfcfb64_0 conda-forge
lzo 2.10 he774522_1000 conda-forge
m2-msys2-runtime 2.5.0.17080.65c939c 3 conda-forge
m2-patch 2.7.5 2 conda-forge
m2w64-gcc-libgfortran 5.3.0 6 conda-forge
m2w64-gcc-libs 5.3.0 7 conda-forge
m2w64-gcc-libs-core 5.3.0 7 conda-forge
m2w64-gmp 6.1.0 2 conda-forge
m2w64-libwinpthread-git 5.0.0.4634.697f757 2 conda-forge
magicgui 0.7.2 pypi_0 pypi
markdown-it-py 3.0.0 pypi_0 pypi
markupsafe 2.1.3 py39ha55989b_0 conda-forge
matplotlib 3.3.4 py39hcbf5309_0 conda-forge
matplotlib-base 3.3.4 py39h581301d_0 conda-forge
matplotlib-inline 0.1.6 pypi_0 pypi
mdurl 0.1.2 pypi_0 pypi
menuinst 1.4.19 py39hcbf5309_1 conda-forge
mkl 2022.1.0 h6a75c08_874 conda-forge
more-itertools 10.0.0 pyhd8ed1ab_0 conda-forge
msys2-conda-epoch 20160418 1 conda-forge
mypy-extensions 1.0.0 pypi_0 pypi
napari 0.4.18 pypi_0 pypi
napari-console 0.0.8 pypi_0 pypi
napari-plugin-engine 0.2.0 pypi_0 pypi
napari-plugin-manager 0.1.0a2 pypi_0 pypi
napari-svg 0.1.10 pypi_0 pypi
nest-asyncio 1.5.6 pypi_0 pypi
networkx 3.1 pyhd8ed1ab_0 conda-forge
npe2 0.7.2 pypi_0 pypi
numpy 1.25.1 py39h816b6a6_0 conda-forge
numpydoc 1.5.0 pypi_0 pypi
opencv-contrib-python 4.8.0.74 pypi_0 pypi
openh264 2.3.1 h63175ca_2 conda-forge
openjpeg 2.5.0 ha2aaf27_2 conda-forge
openssl 3.1.1 hcfcfb64_1 conda-forge
packaging 23.1 pyhd8ed1ab_0 conda-forge
pandas 2.0.3 pypi_0 pypi
parso 0.8.3 pypi_0 pypi
partd 1.4.0 pyhd8ed1ab_0 conda-forge
pcre2 10.40 h17e33f8_0 conda-forge
pickleshare 0.7.5 pypi_0 pypi
pillow 10.0.0 py39ha9166d5_0 conda-forge
pint 0.22 pypi_0 pypi
pip 23.2 pyhd8ed1ab_0 conda-forge
pixman 0.40.0 h8ffe710_0 conda-forge
pkginfo 1.9.6 pyhd8ed1ab_0 conda-forge
platformdirs 3.9.1 pyhd8ed1ab_0 conda-forge
pluggy 1.2.0 pyhd8ed1ab_0 conda-forge
ply 3.11 py_1 conda-forge
pooch 1.7.0 pyha770c72_3 conda-forge
prompt-toolkit 3.0.39 pypi_0 pypi
psutil 5.9.5 py39ha55989b_0 conda-forge
psygnal 0.9.1 pypi_0 pypi
pthread-stubs 0.4 hcd874cb_1001 conda-forge
pthreads-win32 2.9.1 hfa6e2cd_3 conda-forge
pure-eval 0.2.2 pypi_0 pypi
py-lief 0.12.3 py39h99910a6_0 conda-forge
py-opencv 4.7.0 py39hbeae4fa_6 conda-forge
pycosat 0.6.4 py39ha55989b_1 conda-forge
pycparser 2.21 pyhd8ed1ab_0 conda-forge
pydantic 1.10.11 pypi_0 pypi
pygments 2.15.1 pypi_0 pypi
pyopengl 3.1.7 pypi_0 pypi
pyopenssl 23.2.0 pyhd8ed1ab_1 conda-forge
pyparsing 3.1.0 pyhd8ed1ab_0 conda-forge
pyproject-hooks 1.0.0 pypi_0 pypi
pyqt 5.15.7 py39hb77abff_3 conda-forge
pyqt5-sip 12.11.0 py39h99910a6_3 conda-forge
pysocks 1.7.1 pyh0701188_6 conda-forge
python 3.9.16 h4de0772_0_cpython conda-forge
python-dateutil 2.8.2 pyhd8ed1ab_0 conda-forge
python-libarchive-c 5.0 py39hcbf5309_1 conda-forge
python_abi 3.9 3_cp39 conda-forge
pytz 2023.3 pyhd8ed1ab_0 conda-forge
pywavelets 1.4.1 py39hc266a54_0 conda-forge
pywin32 306 pypi_0 pypi
pyyaml 6.0 py39ha55989b_5 conda-forge
pyzmq 25.1.0 pypi_0 pypi
qimage2ndarray 1.8.3 pyhd8ed1ab_0 conda-forge
qt-main 5.15.8 h2c8576c_12 conda-forge
qtconsole 5.4.3 pypi_0 pypi
qtpy 2.3.1 pypi_0 pypi
referencing 0.30.0 pypi_0 pypi
requests 2.31.0 pyhd8ed1ab_0 conda-forge
rich 13.4.2 pypi_0 pypi
ripgrep 13.0.0 h7f3b576_2 conda-forge
rpds-py 0.9.2 pypi_0 pypi
ruamel.yaml 0.17.32 py39ha55989b_0 conda-forge
ruamel.yaml.clib 0.2.7 py39ha55989b_1 conda-forge
scikit-image 0.21.0 pypi_0 pypi
scipy 1.11.1 py39hde5eda1_0 conda-forge
setuptools 68.0.0 pyhd8ed1ab_0 conda-forge
sip 6.7.9 py39h99910a6_0 conda-forge
six 1.16.0 pyh6c4a22f_0 conda-forge
snappy 1.1.10 hfb803bf_0 conda-forge
snowballstemmer 2.2.0 pypi_0 pypi
soupsieve 2.3.2.post1 pyhd8ed1ab_0 conda-forge
sphinx 4.5.0 pypi_0 pypi
sphinxcontrib-applehelp 1.0.4 pypi_0 pypi
sphinxcontrib-devhelp 1.0.2 pypi_0 pypi
sphinxcontrib-htmlhelp 2.0.1 pypi_0 pypi
sphinxcontrib-jsmath 1.0.1 pypi_0 pypi
sphinxcontrib-qthelp 1.0.3 pypi_0 pypi
sphinxcontrib-serializinghtml 1.1.5 pypi_0 pypi
stack-data 0.6.2 pypi_0 pypi
superqt 0.4.1 pypi_0 pypi
svt-av1 1.6.0 h63175ca_0 conda-forge
tbb 2021.9.0 h91493d7_0 conda-forge
tifffile 2023.7.10 pyhd8ed1ab_0 conda-forge
tk 8.6.12 h8ffe710_0 conda-forge
toml 0.10.2 pyhd8ed1ab_0 conda-forge
tomli 2.0.1 pyhd8ed1ab_0 conda-forge
tomli-w 1.0.0 pypi_0 pypi
toolz 0.12.0 pyhd8ed1ab_0 conda-forge
tornado 6.3.2 py39ha55989b_0 conda-forge
tqdm 4.65.0 pyhd8ed1ab_1 conda-forge
traitlets 5.9.0 pypi_0 pypi
typer 0.9.0 pypi_0 pypi
typing-extensions 4.7.1 hd8ed1ab_0 conda-forge
typing_extensions 4.7.1 pyha770c72_0 conda-forge
tzdata 2023.3 pypi_0 pypi
ucrt 10.0.22621.0 h57928b3_0 conda-forge
urllib3 2.0.3 pyhd8ed1ab_1 conda-forge
vc 14.3 h64f974e_17 conda-forge
vc14_runtime 14.36.32532 hfdfe4a8_17 conda-forge
vispy 0.12.2 pypi_0 pypi
vs2015_runtime 14.36.32532 h05e6639_17 conda-forge
wcwidth 0.2.6 pypi_0 pypi
wheel 0.40.0 pyhd8ed1ab_1 conda-forge
win_inet_pton 1.1.0 pyhd8ed1ab_6 conda-forge
wrapt 1.15.0 pypi_0 pypi
x264 1!164.3095 h8ffe710_2 conda-forge
x265 3.5 h2d74725_3 conda-forge
xorg-libxau 1.0.11 hcd874cb_0 conda-forge
xorg-libxdmcp 1.1.3 hcd874cb_0 conda-forge
xz 5.2.6 h8d14728_0 conda-forge
yaml 0.2.5 h8ffe710_2 conda-forge
zfp 1.0.0 h63175ca_3 conda-forge
zipp 3.16.2 pyhd8ed1ab_0 conda-forge
zlib 1.2.13 hcfcfb64_5 conda-forge
zlib-ng 2.0.7 hcfcfb64_0 conda-forge
zstandard 0.19.0 py39h95af829_2 conda-forge
zstd 1.5.2 h12be248_7 conda-forge

I have been able to use tkkinter to have my pop up dialogs but in the future I would like to make more elaborate dialog boxes to tweak image processing parameters so I would like MagicGui to work. I also posted this issue here: https://forum.image.sc/t/having-trouble-with-unresponsive-magicgui-dialog-boxes-in-jupyter-notebook/84202/1.

Thank you very much,

William J Nicolas

**Comment by tlambert03** [comment]
answered at https://forum.image.sc/t/having-trouble-with-unresponsive-magicgui-dialog-boxes-in-jupyter-notebook/84202/2
