### ISSUE TITLE
Indeterminate progress bars

### ISSUE THREAD

**Issue by GenevieveBuckley** [pyapp-kit/magicgui#577]
**Describe the bug**
magicgui has strange, unwanted behaviour when you try and use indeterminate progress bars.

tqdm allows indeterminate progress bars (i.e. a "busy" indicator for users even when the total number of iterations or run time is not known ahead of time). This is activated passing the keyword argument `tqdm(total=None)`.

I tried to use this feature from the magicgui tqdm wrapper, but observed some strange behaviour. Can you help me figure out why? Thank you 😄 

**To Reproduce**
```python
import time
from magicgui import magicgui
from magicgui.tqdm import tqdm

@magicgui(call_button=True, layout="horizontal")
def long_running(sleep_time=5):
    """Long running computation with range iterator."""
    with tqdm(total=None) as pbar:
        pbar.update
        time.sleep(sleep_time)
    print("Done")

long_running.show(run=True)
```

1. Run the python script above.
2. Click the "Run" button in the magicgui widget that is displayed.
3. Observe a five second delay after clicking the run button, where no progress bar is displayed. After five seconds, observe that the word 'Done' is printed to the terminal and *now* an indeterminate progress bar is displayed in the napari widget... forever. It never actually stops the indeterminate progress bar, after only having started it *after* the slow function finished running.

**Expected behavior**
I expected the indeterminate progress bar to be visible and activate after clicking the "Run" button, for the period of time required by the function to complete the sleep statement.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Mac]: Mac Ventura
 - backend: [e.g. Qt 5.13.0] pyqt 5.15.7; qtpy 2.3.1; superqt 0.4.1
 - magicgui version [e.g. 0.1.0] magicgui main branch

**Comment by tlambert03** [comment]
it's because the long function is invoked and immediately blocks the running thread, so the GUI doesn't have time to actually show the progress bar before it's blocked.  You need to invoke your long running function inside of a thread.  For example:

```python
import time

from superqt.utils import thread_worker

from magicgui import magicgui
from magicgui.tqdm import tqdm


@magicgui(call_button=True, layout="horizontal")
def long_running(sleep_time=1):
    """Long running computation with range iterator."""
    with tqdm() as pbar:

        @thread_worker(connect={"finished": lambda: pbar.progressbar.hide()})
        def sleep(secs):
            time.sleep(secs)

        sleep(sleep_time)

long_running.show(run=True)
```

**Comment by tlambert03** [comment]
there's another pattern for using magicgui with superqt in the napari repo as well:  https://github.com/napari/napari/blob/main/examples/mgui_with_threadworker_.py

**Comment by GenevieveBuckley** [comment]
Thank you! I've been trying to put the thread worker decorator in the wrong place
