### ISSUE TITLE
Add support for toolbars

### ISSUE THREAD

**Issue by larsoner** [pyapp-kit/magicgui#593]
It is possible to create toolbars on both Qt and in notebooks, e.g, this is what we have in MNE-Python:

![](https://github.com/pyapp-kit/magicgui/assets/2365790/fda3ddec-b70d-4428-8384-3389f741d27e)

![](https://github.com/pyapp-kit/magicgui/assets/2365790/9a9ee33c-78d7-43dd-b0fc-d3730146dacc)

It would be great if magicgui could support both. I might be up for implementing these since I already have some relevant abstraction code.

**Comment by tlambert03** [comment]
yes please! 

I just took a look at `mne.viz.backends._abstract` and indeed can see quite a bit of similarity with magicgui.  I like how you've laid it out, and can see a lot of potential for improving magicgui with similar patterns.

as you take a look at the backend implementations here, if you feel like major changes would be needed anywhere to do what you want, let me know.  I'm definitely open to it... and fortunately, most of the backend protocols and ABCs are largely hidden from the user-facing API, so it should be possible to rearrange stuff without many breaking changes

**Comment by tlambert03** [comment]
I'm going to start working on this 👍
