### ISSUE TITLE
How can we programatically intercept keystokes like `delete` in a magicgui table?

### ISSUE THREAD

**Issue by cudmore** [pyapp-kit/magicgui#623]
Hi Tally and all,

Thanks so much for your work on magicgui, it is super exciting and an amazing addition to the package ecosystem for Python GUIs!

**Describe the bug**
We are implementing a derived class from the magicgui `table` and are having trouble programmatically intercepting keystrokes like `delete`.

When the user hits `delete`, it always deletes the value in the selected cell (or row) with no callback?

**Desired Action**
We want to catch the `delete` keystroke so we can take a custom action.

**Attempted Solutions**
We tried to intercept the keystroke using the inherited PyQt QWidget with `keyPressEvent(event)` but this never gets called?

We are able to turn off `double click` edit in a cell in our derived class using

    self.native.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

How do we turn off keystrokes like `delete` and add a custom callback?

**Environment :**
 - OS: macOS Ventura 13.3.1 (a)
 - backend: PyQt5==5.15.10, PyQt5-Qt5==5.15.11
 - magicgui version: 0.8.1

**To Reproduce**
Here is a minimal working example:

```python
import sys
import pandas as pd
from qtpy import QtWidgets
from magicgui.widgets import Table

class myMagicTable(Table):
    def __init__(self, data : pd.DataFrame):
    
        super().__init__(data)

        # turn off editing of single cells
        # this turns off double click to edit cell -->> awesome
        # Bug: does not turn off keyboard events like 'delete' ???
        self.native.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        # Bug: disabled above with NoEditTriggers
        #   self._changed still gets called on keyboard 'delete'
        self.changed.connect(self._changed)

    def _changed(self, items : dict):
        """This is to respond to user editing a cell.
                
        BUG
        ---
        This gets called multiple times on user pressing 'delete' key ...

        We want to fix this by (for example)
           intercepting delete key in self.keyPressEvent()
        """
        print('_changed() items is:')
        print('   ', items)
            
    def keyPressEvent(self, event):
        """Inherited PyQt member function
        
        Never gets called, expect this to get called on key press (core PyQt)
        This is part of magicgui via self.native. How do we patch in to this?
        We want magic gui to ignore keyboard 'delete' and instead emit a signal
        """
        print('keyPressEvent()')
        print(event)
        # self.emitOurSigal.emit( ...)
        
def openTable():
    """Open a magic gui table with a pandas dataframe.
    """
    # make a simple dataframe with 4 rows and 4 columns
    data = pd.DataFrame(columns=['a', 'b', 'c', 'd'])
    data['a'] = [1,2,3,4]
    data['b'] = [8,7,6,5]
    data['c'] = ['a','b','c','d']

    table = myMagicTable(data)

    table.show()

def main():
    app = QtWidgets.QApplication([])
    openTable()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
```

**Comment by tlambert03** [comment]
hey @cudmore, thanks for opening.

As you've found, I'm afraid magicgui doesn't really offer much yet in the way of keybinding abstractions.  This means you will need to modify the backend widget directly.  Your comment in `keyPressEvent` suggests you know this already, but just for the sake of completeness: `magicgui.widget.Widget` subclasses are *not* themselves QWidgets.  Rather, they are abstraction layers that control some backend widget, (which might be a QWidget but could vary depending on whether you're using magicgui in a jupyter notebook for example).  You can access the backend widget at `widget.native`.   So, to modify your example slightly, you don't want to override `Table.keyPressEvent`, you need to override `Table.native.keyPressEvent`:

```python
from magicgui.widgets import Table
from qtpy.QtCore import Qt

class myMagicTable(Table):
    def __init__(self, data):
        super().__init__(data)

        # patch in our own keyPressEvent
        self._originalKeyPressEvent = self.native.keyPressEvent
        self.native.keyPressEvent = self._custom_key_press_event

    def _custom_key_press_event(self, event):
        if event.key() in (Qt.Key.Key_Delete, Qt.Key.Key_Backspace):
            print("doing something special here")
            return
        self._originalKeyPressEvent(event)


if __name__ == "__main__":
    data = {"a": [1, 2, 3, 4], "b": [8, 7, 6, 5], "c": ["a", "b", "c", "d"]}
    table = myMagicTable(data)
    table.show(run=True)
```

let me know if that gets your issue solved or if new stuff comes up

**Comment by cudmore** [comment]
Hi Talley, thanks so much for the fix, it worked like a charm! I should have though of it :)

**Comment by tlambert03** [comment]
glad it helped.  will close, but feel free to ask more questions
