### ISSUE TITLE
No parent with parent_changed

### ISSUE THREAD

**Issue by aeisenbarth** [pyapp-kit/magicgui#627]
**Describe the bug**

The `parent` attribute seems to be always None and event handlers for `parent_changed` receive None.

**To Reproduce**

```python
from magicgui.widgets import Container
import napari
viewer = napari.viewer.Viewer()
dock = Container()
def on_parent_changed(parent):
    print(f"parent_changed: {parent=}, {dock.parent=}")
    if parent is not None: # and visible etc.
        print("setup")
    else:
        print("cleanup")
dock.parent_changed.connect(on_parent_changed)
qt_dock = viewer.window.add_dock_widget(dock)
# Expected: "parent_changed: parent=<QtViewerDockWidget>, dock.parent=<QtViewerDockWidget>"
assert dock.parent is not None
# Click the close button, or remove the dock programmatically
viewer.window.remove_dock_widget(qt_dock)
# Expected: "parent_changed: parent=None, dock.parent=None"
assert dock.parent is None
```

**Expected behavior**

When `parent_changed` is triggered on hooking a widget into the Napari widgets tree, the parent should be passed and the parent attribute should be set. When the parent is removed, None should be passed.

Specifically, the example code would print
```
parent_changed: parent=<napari._qt.widgets.qt_viewer_dock_widget.QtViewerDockWidget object at 0x7fe02ce5a310>, dock.parent=<napari._qt.widgets.qt_viewer_dock_widget.QtViewerDockWidget object at 0x7fe02ce5a310>
setup
parent_changed: parent=None, dock.parent=None
cleanup
```
This works in napari<=0.4.19 and magicgui==0.7.3, but breaks with magicgui>=0.8.0.

**Context**

My use case is that my plugin's dock is supposed to do setup and cleanup when the dock becomes visible or is removed. This was previously necessary because dock instances were just hidden and reused when opening again. I had code that would listen for the _visibilityChanged_ event on the Qt parent, which I can only register after a parent was added. 

What I am really interested is being notified when the dock is shown or not shown anymore.
Possibly there is now a better way to do it, or a Napari API with dock activated/visible and deactivated/hidden hooks (I am not aware of).

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - backend: PyQt5==5.15.10
 - magicgui==0.8.1

**Comment by tlambert03** [comment]
thanks @aeisenbarth.  I can confirm the problem.  I think this might be butting up against the needs of https://github.com/pyapp-kit/magicgui/issues/456, https://github.com/pyapp-kit/magicgui/issues/582, and https://github.com/pyapp-kit/magicgui/pull/583

in those issues, it was concluded/enforced that `Widget.parent` would point to a magicgui widget (and not a backend widget).  (I think that's how that attribute probably should be, and if you want the backend parent I think it should be accessed via `widget.native`).  

However, i also definitely agree that there's a need to know when a magicgui widget.native has been placed into a non-magicgui backend widget (such as in napari).  I need a little time to sit and look closer at the code and I'll get back to you as soon as I can
