### ISSUE TITLE
ListEdit widget buttons should be nested and always use horizontal layout

### ISSUE THREAD

**Issue by jni** [pyapp-kit/magicgui#636]
When using a ListEdit for multiple selections of a dropdown, horizontal layout takes a *ton* of space, but changing it to vertical layout results in rather oversized buttons:

<img width="378" alt="Screenshot 2024-03-14 at 6 10 02 pm" src="https://github.com/pyapp-kit/magicgui/assets/492549/e8c4d54e-6624-4d9c-a906-66f422449cea">

I think a sensible default here would be a vertical layout with the buttons nested inside a horizontal layout, but possibly other suggestions would also work.

**Comment by hanjinliu** [comment]
Hi @jni ,
I implemented ListEdit in a very simple way, so the layout of the buttons definitely needs some improvement. I like your idea that the buttons should be horizontally aligned.

I think the default layout of the child widgets should be horizontal, considering the default layout of Containers is vertical. A vertical ListEdit inside a vertical Container makes it hard to distinguish which widget is for which parameter.

I would like to propose a better layout, though (below). It's much intuitive to add minus buttons for each child component and the plus button at the position where next child component will be. This design has been adopted in many places, such as the tab bar of Google Chrome.

```
* vertical

[ child widget 0 ] [-]
[ child widget 1 ] [-]
[ child widget 2 ] [-]
[          +         ]

* horizontal

[ child widget 0 ] [-]  [ child widget 1 ] [-]  [ child widget 2 ] [-]  [  +  ]

```

But either way, I'm happy to make a PR to update them.

**Comment by jni** [comment]
Thanks for the response @hanjinliu, and I have to say I really like your idea!
