### ISSUE TITLE
ComboBox with sections

### ISSUE THREAD

**Issue by qin-yu** [pyapp-kit/magicgui#637]
Hi, I am now adding a separator to split the dropdown list into two parts by calling `.native.insertSeparator(n)`. It would be nice to have a dropdown list with multiple sections with names. If it's considered a bad idea then nevermind. If no one has time, maybe I can contribute.

**Comment by qin-yu** [comment]
First attempt:

- #638

**Comment by qin-yu** [comment]
> i would consider a PR to that effect! :)
>
> not exactly sure how I'd want it implemented. Perhaps a special `magicgui.Separator()` sentinel that could be used to indicate it? open to thoughts

Thank you for your encouragement and advice. I explored the capabilities of magicgui further and experimented with the limitations posed by QComboBox. Following your suggestion, I implemented a Separator class/object, which indeed successfully addressed the issue at hand. Initially, I also envisioned integrating section names alongside each separator. However, it appears that QComboBox inherently lacks support for this functionality.

I considered employing workarounds, such as utilizing muted ComboBox items as makeshift section headers, but such approaches seem inelegant and potentially problematic. If you believe there's merit in pursuing this further, I’m open to discussing potential strategies. Otherwise, I feel we might have reached the practical extent of what we can achieve under the current limitations.

**Comment by tlambert03** [comment]
> However, it appears that QComboBox inherently lacks support for this functionality.

yeah, QCombBox doesn't have support for groups.  If you did implement something like that, i would say it would be a better fit for [superqt](https://github.com/pyapp-kit/superqt) ... and then we would just wrap it here.  That said, I agree that it's likely difficult to implement in an elegant and robust way.  Moreoever, it's unlikely that most of the other gui backends that magicgui would ever want to support would have it either, so let's consider that as an independent issue from this one

**Comment by qin-yu** [comment]
> so let's consider that as an independent issue from this one

Understood and thanks for the guidance. Regarding the next steps, it seems the [Codecov Report](https://github.com/pyapp-kit/magicgui/pull/638#issuecomment-1997773575) is asking for increased test coverage for the updates I've submitted. I'll proceed by writing two tests I guess. Does this sound like the right thing to do?

**Comment by tlambert03** [comment]
closed by #638
