### ISSUE TITLE
Dropdown list from ipynb allows duplicates but ComboBox from Qt only keep unique item names

### ISSUE THREAD

**Issue by qin-yu** [pyapp-kit/magicgui#639]
**Describe the bug**
Dropdown list from ipynb allows duplicates. E.g. [1, 2, 3, 3] will show in the Dropdown list as 1, 2, 3, 3. I guess this is considered a bug?

**Expected behavior**
I would expect it to be 1, 2, 3 only because Qt backend does so

**Comment by tlambert03** [comment]
actually, that sounds to me like a bug in our Qt backend...  Qt itself has no problem with this:

```python
from qtpy.QtWidgets import QComboBox, QApplication

app = QApplication([])
combo = QComboBox()
combo.addItems(['a', 'b', 'c', 'c'])
combo.show()
app.exec_()
```

<img width="164" alt="Screenshot 2024-03-18 at 1 58 17 PM" src="https://github.com/pyapp-kit/magicgui/assets/1609449/fe71a420-6566-45b9-907d-f36cd156b6e3">


specifically, i would expect this to work fine:

```python
from magicgui.widgets import ComboBox

# two different data values for c
box = ComboBox(choices=[("a", 0), ("b", 1), ("c", 2), ("c", 3)])

box.show(run=True)
```

but it doesn't because the `ComboBox._mgui_set_choices` implementation only looks at the name.   Haven't dug too deeply there yet, but i'm not sure we should impose the restriction if both Qt and ipynb don't

**Comment by qin-yu** [comment]
The implementation now is to have unique choice names https://github.com/pyapp-kit/magicgui/blob/781a54a3d0fb49845ededf734dbf30f71e18509c/src/magicgui/backends/_qtpy/widgets.py#L938

Do you want to change this?

**Comment by qin-yu** [comment]
Yeah neither backend limit such use. Let's lift this restriction

**Comment by qin-yu** [comment]
It appears that modifying the current implementation of the Qt ComboBox resulted in 3 failures among the original tests:

```python
=========================== short test summary info ============================
FAILED tests/test_container.py::test_reset_choice_recursion - assert (0, 0, 1... <- original
FAILED tests/test_widgets.py::test_separator[ipynb] - assert (1, 2, 4, 6, 7, ... <- new test
FAILED tests/test_widgets.py::test_separator[qt] - AssertionError: assert 21 ... <- new test
FAILED tests/test_widgets.py::test_unhashable_choice_data - AssertionError: a... <- original
FAILED tests/test_widgets.py::test_categorical_change_choices[ComboBox] - ass... <- original
============= 5 failed, 357 passed, 22 skipped, 1 xfailed in 7.36s =============
```

I guess these changes would lead to a minor release? Let's consider another PR later this week if necessary. For #638, let's retain the original implementation. What do you think? 🤔

**Comment by tlambert03** [comment]
i agree!

**Comment by qin-yu** [comment]
If we allow multiple items with the same name, how would this impact the ability for users to select options by name?
