### ISSUE TITLE
File dialog in background

### ISSUE THREAD

**Issue by aeisenbarth** [pyapp-kit/magicgui#642]
Depending on the windowing system, file dialogs are opened in the background.

As a consequence:
- the user does not notice that the file dialog was successfully opened, especially when the application window was maximized
- the originating window (Napari, MagicGUI dialog) is blocked (as expected), and the user cannot click the file button again
- every time, an extra click is necessary to bring the file dialog in foreground before choosing a file

**To Reproduce**
I've had this for over a year consistently on one system:
- ✓ Ubuntu with **X11** windowing system (X.Org X Server 1.21.1.4, X Protocol Version 11)
- ✗ But not on a virtualized system with Xvnc (and no Xorg display server).
- ✗ I have not tested on Wayland.
- ✗ I have not tested on Windows/macOS.

1. Run this code
  ```python
  from magicgui.widgets import Container, FileEdit
  from PyQt5.QtCore import Qt
  
  file_edit = FileEdit(label="File path")
  container = Container(widgets=[file_edit])
  qt_widget = container.native
  qt_widget.setWindowState(Qt.WindowMaximized)
  container.show(run=True)
  ```
2. Click <kbd>Select file</kbd>

**Expected behavior**
The file dialog should be opened in foreground.

It should not show as a separate application in the dock (with default "gear" icon), but be a child window of the originating application.

**Screenshots**

![image](https://github.com/pyapp-kit/magicgui/assets/54448967/774ed640-811b-4c37-a057-c01e4a0a3301)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - backend: Qt 5.15.9
 - magicgui version: 0.8.2

**Comment by aeisenbarth** [comment]
I initially thought the cause could be that magicgui does not pass any (native) parent widget in `FileEdit._show_file_dialog(…)`. But when I add the parent argument the issue is not resolved, although the Qt API seems to be used correctly now.
```python
        result = self._show_file_dialog(
            self.mode,
            caption=self._btn_text,
            start_path=_start_path,
            filter=self.filter,
            parent=self.native,
        )
```

And when I pass `options=PyQt5.QtWidgets.QFileDialog.DontUseNativeDialog` the issue goes away.

So it might have another cause within Qt or the windowing system, hoping it goes away with a system upgrade or Wayland.

**Comment by tlambert03** [comment]
hey @aeisenbarth.  my guess is that this is indeed a deeper issue with Qt and windowing systems.  But just to verify that, can you check this Qt-only code that simulates what magicgui would be doing?

```pythonfrom qtpy.QtCore import Qt
from qtpy.QtWidgets import (
    QApplication,
    QFileDialog,
    QHBoxLayout,
    QLineEdit,
    QPushButton,
    QWidget,
)

app = QApplication([])

wdg = QWidget()
layout = QHBoxLayout(wdg)
layout.addWidget(QLineEdit())
btn = QPushButton("Select file")
layout.addWidget(btn)
wdg.setWindowState(Qt.WindowMaximized)


@btn.clicked.connect
def show_dialog() -> None:
    result = QFileDialog.getOpenFileName(wdg, "Choose a file")
    print(result)


wdg.show()
app.exec()

**Comment by aeisenbarth** [comment]
I can verify it with the pure qtpy code. 

It happens with:
- ✓ PyQt5
- ✓ PySide2 (Qt5)
- ✗ not with pure C++ (Qt5.15) <details><summary>code</summary>

  ```c++
  #include <QApplication>
  #include <QHBoxLayout>
  #include <QLineEdit>
  #include <QPushButton>
  #include <QFileDialog>
  #include <iostream>

  int main(int argc, char *argv[]) {
      QApplication app(argc, argv);

      QWidget wdg;
      QHBoxLayout layout(&wdg);

      QLineEdit lineEdit;
      layout.addWidget(&lineEdit);

      QPushButton btn("Select file");
      layout.addWidget(&btn);

      wdg.setWindowState(Qt::WindowMaximized);

      QObject::connect(&btn, &QPushButton::clicked, [&]() {
          QString fileName = QFileDialog::getOpenFileName(&wdg, "Choose a file");
          std::cout << fileName.toStdString() << std::endl;
      });

      wdg.show();
      return app.exec();
  }

  ```

  </details>
- ✗ not with PyQt6
- ✗ not with PySide6

So it is an issue with the Python bindings and fixed in newer versions.

Since it is not in any way a MagicGUI issue, we can close it.

**Comment by tlambert03** [comment]
thank you for taking such a thorough look!  One thing I will say is that if you can find a good workaround (such as *not* using the static methods of the dialog, but rather instantiating a widget, and calling `raise_()` on it), I'm happy to change the code here so that it works in all cases
